import pandas as pd
import numpy as np
animalset={'animals':["cat","dog","rabbit"],'age':[3,7,2]}
myvar=pd.DataFrame(animalset)
print(myvar)
print("--"*50)
a=[1,7,2,9]
series=pd.Series(a)
print(series)
print("--"*50)
print(series[0])
print("--"*50)
myvar=pd.Series(a,index=["x","y","z","a"])
print(myvar)
print("--"*50)
calories={"day1":420,"day2":380,"day3":390}
myvar=pd.Series(calories)
print(myvar)
print("--"*50)
ser=pd.Series()
print(ser)
print("--"*50)
data=np.array(["egg","corn","milk","cheese","lentils","sugar"])
ser=pd.Series(data)
print(ser)
print("--"*50)
data={
"calories":[420,380,390],
"duration":[50,40,45]
}

df=pd.DataFrame(data)
print(df)
print("--"*50)
df=pd.DataFrame(data,index=["day1","day2","day3"])
print(df)
print(df.loc["day2"])
print("--"*50)
df=pd.read_csv('student_practice_data.csv')
print(df)
print("--"*50)
